server:
  port: 9000
spring:
  kafka:
    consumer:
      client.id: client2
      bootstrap-servers: localhost:9092
      group-id: consumerGroup3
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
